name: Node App

on:
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: [self-hosted, rnd]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Run Docker Compose
      working-directory: docker-node
      run:  docker compose up -d
