name: Deploy Node Application

on:
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: [self-hosted, rnd]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: List files
      run:  ls -al

    - name: Run Docker Compose
      run:  docker compose up -d
